### ISSUE TITLE
Nav bar & support button & cookie footer will shift position after clicked

### ISSUE THREAD

**Issue by Zijian-Wang** [milvus-io/milvus.io#1013]
There is a noticeable shift of the nav bar & support button (bird on the bottom right corner) when the select language button is clicked (or the support button is clicked)

**Nav bar position shift:**
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/19564332/160332026-d3a64636-8e5c-4092-bf43-8d3a40da78e7.png">
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/19564332/160332060-b3572fe0-219f-4aaa-876f-001fc0547802.png">

**Support button position shift:**
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/19564332/160332323-d01da1a6-10cc-40e2-9e49-4b03863dac88.png">
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/19564332/160332342-847cf5e7-4bad-4e1d-837e-cfbbbbc017f6.png">

I'm using chrome on mac, but it is also present on safari.

It seems that all these elements will extend right and take up the space of the scroll bar when buttons are clicked.

**Comment by shanghaikid** [comment]
The chat bot is removed. so, we will close the issue since it no longer exits.
