### ISSUE TITLE
Slack link

### ISSUE THREAD

**Issue by mausch** [milvus-io/milvus.io#1079]
Hi, the link to Slack in https://milvus.io/docs/v2.1.x/product_faq.md#Still-have-questions takes me to a page where I can join only if I have an email in the zilliz.com domain. 
The page says: "Don’t have an @zilliz.com email address? Contact the workspace administrator at milvus.io for an invitation."

I think this link should be replaced with an invite link?

Thanks

**Comment by YiyunNi** [comment]
Hi @mausch , thanks for pointing out the issue! I have updated the Slack invite link in this [PR](https://github.com/milvus-io/milvus-docs/pull/1771).
