### ISSUE TITLE
Modify the verbiage of the navigation bar in the doc pages

### ISSUE THREAD

**Issue by gujun720** [milvus-io/milvus.io#506]
Now:
Edit this page.
Create a doc issue.
Create a project issue.
Question. Slack us.

Please change to:
Edit this page.
Discuss it on GitHub. (https://github.com/milvus-io/milvus/discussions/new)
Report a bug.
Join Slack channel.

**Comment by ThyeeZz** [comment]
en：
![image](https://user-images.githubusercontent.com/41352919/124244056-2258a200-db51-11eb-8952-1583f8762c0e.png)
cn：
![image](https://user-images.githubusercontent.com/41352919/124244104-2b497380-db51-11eb-8326-08668d40ec7f.png)

**Comment by gujun720** [comment]
The link of 'Join Slack channel' should be 
https://join.slack.com/t/milvusio/shared_invite/zt-e0u4qu3k-bI2GDNys3ZqX1YCJ9OM~GQ

**Comment by ThyeeZz** [comment]
![image](https://user-images.githubusercontent.com/41352919/124910804-977b1a00-e01e-11eb-993e-62affdc5b8d3.png)
