### ISSUE TITLE
Turn brand logos into gray color on www.milvus.io

### ISSUE THREAD

**Issue by PahudPlus** [milvus-io/milvus.io#538]
This is a common practice. And the current logo wall looks tremendously flamboyant!

**Comment by PahudPlus** [comment]
Examples: 
- https://www.agora.io/en/
- https://www.cockroachlabs.com/
- https://www.snowflake.com/customers/
- https://www.okta.com/

**Comment by shanghaikid** [comment]
closed, thanks.
