### ISSUE TITLE
Add a footer to the milvus site.

### ISSUE THREAD

**Issue by YiyunNi** [milvus-io/milvus.io#567]
Could you please add a webpage footer on Milvus.io?

**Comment by shanghaikid** [comment]
![image](https://user-images.githubusercontent.com/185051/125888004-07b1d8e0-bbe0-4cab-ab71-e986f28d8084.png)
This is the footer

**Comment by YiyunNi** [comment]
> ![image](https://user-images.githubusercontent.com/185051/125888004-07b1d8e0-bbe0-4cab-ab71-e986f28d8084.png)
> This is the footer

 I meant something like this.

![截屏2021-07-16 11 38 24](https://user-images.githubusercontent.com/74396087/125888165-d5f9993e-3b0d-4a2e-8561-3c1918724520.png)

**Comment by shanghaikid** [comment]
What is the content ? 
In milvus.io, all these links are ready placed on the top nav.  Why do we put duplicated links on footer? 

In zilliz.com, we have links in sub-nav, so we place some useful links on footer.

**Comment by YiyunNi** [comment]
Ah okay. This makes sense. But one more question, can we add the channels (twitter, linkedin, slack, etc.). in the footer?
