### ISSUE TITLE
add automatic release after merging/at a fixed interval for milvus-docs

### ISSUE THREAD

**Issue by LocoRichard** [milvus-io/milvus.io#572]
Can you guys set up an automation plug-in for milvus-docs that can release the content after merging or at a fixed interval (once a day for instance)? It could be labouring for doc maintainers to release everytime when changes were merged into each branch. Thank you!

**Comment by shanghaikid** [comment]
@nameczz  Lets release milvus doc every 2 hour.

**Comment by nameczz** [comment]
@LocoRichard 

I don't think we need release every branch. So which branch need to release every 2 hour? May be master?

**Comment by LocoRichard** [comment]
@nameczz 
Releasing every two hours might be overdoing for the current situation. The real inconvenience here is that, first, **v2.0.0** needs a frequent, yet not significant most of time, maintenance, and second, the **three branches of v1.x** usually require the same modifications and we have release thrice at a time. I'd suggest that automatic release for each branch after merging, or, if the former is possible, v2.0.0 release twice a day, and each branch of v1.x once a day.

**Comment by nameczz** [comment]
OK, docs will trigged by merge not released in future.
