### ISSUE TITLE
Typo in blog article banner

### ISSUE THREAD

**Issue by claireyuw** [milvus-io/milvus.io#882]
![image](https://user-images.githubusercontent.com/83751381/149609191-6bed81e0-207c-4382-abef-d9e476a0fc5f.png)

Should be "Hacktoberfest"

**Comment by nameczz** [comment]
Should fix it in blog article file in web-content repo

**Comment by sutcalag** [comment]
Should fix img from assets.zilliz.com/hacktoberfestrelease_695f45bb41.png
